before:
  hooks:
    - go mod download
builds:
  - env:
      # It must remain portable
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
archives:
  # We only build the downloadable binary
  - format: binary
    # No version for easier download using "latest"
    name_template: "{{.Binary}}_{{.Os}}_{{.Arch}}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: RedHatInsights
    name: haberdasher
  prerelease: auto
